import main
from flask import Blueprint

vm_routes = Blueprint('/controller', __name__)

vm_routes.add_url_rule(
    'tours',
    'tour/create_tour',
    main.add_programtour,
    methods=['POST'],
)
vm_routes.add_url_rule(
    'tours',
    'tour',
    main.select_programtour,
    methods=['GET'],
)
vm_routes.add_url_rule(
    'tours',
    'tour/edit_tour',
    main.put_programtour,
    methods=['PUT'],
)
vm_routes.add_url_rule(
    'tours',
    'tour/delete_tour',
    main.delete_programtour,
    methods=['DELETE'],
)
vm_routes.add_url_rule(
    'users',
    'register_users',
    main.register_user,
    methods=['POST'],
)
vm_routes.add_url_rule(
    'users',
    'select_user',
    main.select_user,
    methods=['GET'],
)
vm_routes.add_url_rule(
    'allusers',
    'selectall_user',
    main.selectall_user,
    methods=['GET'],
)
vm_routes.add_url_rule(
    'users',
    'update_users',
    main.update_user,
    methods=['PUT'],
)
vm_routes.add_url_rule(
    'login',
    'login',
    main.login,
    methods=['POST'],
)
vm_routes.add_url_rule(
    'histories',
    'histories',
    main.add_history,
    methods=['POST'],
)
vm_routes.add_url_rule(
    'histories',
    'histories/get_history',
    main.select_history,
    methods=['GET'],
)
vm_routes.add_url_rule(
    'login',
    'users/password/edit',
    main.edit_password,
    methods=['PUT'],
)
vm_routes.add_url_rule(
    'reports',
    'report_tour',
    main.report_tour,
    methods=['GET'],
)
vm_routes.add_url_rule(
    'histories',
    'histories/update_history',
    main.update_history,
    methods=['PUT'],
)